# Juan Manuel Deutsch, Cesar Felipe Giraldo, Julian Felipe Pulido

# Exercise 1.2

## A

In [13]:
import numpy as np

In [14]:
D = np.array([[5, 2], [9, 7], [6, 1]])
print("\nMatriz base:")
print(D)
DT = D*2
print("\nMatriz base transformada:")
print(DT)

CD = np.cov(D, rowvar=False, bias=True)
print("\nCovarianza de la matriz base:")
print(CD)
CDT = np.cov(DT, rowvar=False, bias=True)
print("\nCovarianza de la matriz base transformada:")
print(CDT)

#Se pone rowvar (Variable de fila) en falso, ya que nuestras variables estan representadas por columnas, no por filas y bias en true para que el denominador no sea N-1 si no N


Matriz base:
[[5 2]
 [9 7]
 [6 1]]

Matriz base transformada:
[[10  4]
 [18 14]
 [12  2]]

Covarianza de la matriz base:
[[2.88888889 4.11111111]
 [4.11111111 6.88888889]]

Covarianza de la matriz base transformada:
[[11.55555556 16.44444444]
 [16.44444444 27.55555556]]


Tenemos la matriz D, la base de nuestro ejercicio y tenemos la transformación DT, multiplicando cada dato de la matriz por 2, para luego calcular las covarianzas de ambas matrices mostrando que la transformacion de los datos puede cambiar el resultado de la covarianza

## B

Para una transformación afin que es $$f_j(x) = ax + b$$ para el calculo de la media y covarianza de la matriz transformada seria:

Media:
$$μ_{j}t = 1/n\sum_{i=1}^nf_j(D_{i,j})=1/n\sum_{i=1}^aμ_j+b=aμ_j+b$$

Covarianza:
$$σ_{ij}t = 1/n\sum_{k=1}^n(f_i(D_{k,i}) - μ_{j}t)(f_j(D_{k,j})-μ_{j}t)$$
$$=1/n\sum_{k=1}^na_ia_j(σ_{ij})$$
$$=a_ia_jσ_{ij}$$

Donde $μ_{j}t$ es la media de la matriz transformada, $μ_j$ la media de la matriz base, $σ_{ij}t$ es la covarianza de la matriz transformada y $σ_{ij}$ la covarianza de la matriz base

## C

La correlación entre $X_i$ y $X_j$ de la matriz transformada y la matriz base:

$$ρ_{ij}t = σ_{ij}t/\sqrt{σ_{ii}tσ_{jj}t} = a_ia_jσ_{ij}/\sqrt{a_{i}^2σ_{ii}*a_{j}^2σ_{jj}} = σ_{ij}/\sqrt{σ_{ii}σ_{jj}} = ρ_{ij}$$

Donde $ρ_{ij}t$ es la correlación transformada y $ρ_{ij}$ es la correlación base

La propiedad demuestra que la correlacion entre dos variables no cambia despues de una tranformación afín