# Exercise 1.2

## A

In [2]:
import numpy as np

In [21]:
D = np.array([[5, 2], [9, 7], [6, 1]])
print(D)
DT = D*2
print(DT)

CD = np.cov(D, rowvar=False)
print(CD)
CDT = np.cov(DT, rowvar=False)
print(CDT)

#Se pone rowvar (Variable de fila) en falso, ya que nuestras variables estan representadas por columnas, no por filas

[[5 2]
 [9 7]
 [6 1]]
[[10  4]
 [18 14]
 [12  2]]
[[ 4.33333333  6.16666667]
 [ 6.16666667 10.33333333]]
[[17.33333333 24.66666667]
 [24.66666667 41.33333333]]


Tenemos la matriz D, la base de nuestro ejercicio y tenemos la transformación DT, multiplicando cada dato de la matriz por 2, para luego calcular las covarianzas de ambas matrices mostrando que la transformacion de los datos puede cambiar el resultado de la covarianza

## B

In [34]:
a = 10
b = 5

DTA = a * D + b
print("Matriz transformada afin:")
print(DTA)

mu = np.mean(D, axis=0)
print("\nMedia de la matriz base:")
print(mu)

mut = np.mean(DTA, axis=0)
print("\nMedia de la matriz afin:")
print(mut)
#Se pone axis = 0 para que calule la media de cada columna

print("\nCovarianza de la matriz base:")
print(CD)

CDTA = np.cov(DTA, rowvar=False)
print("\nCovarianza de la matriz afin:")
print(CDTA)

mut_esperado = a * mu + b
print("\nMedia de la matriz afin esperada:")
print(mut_esperado)

CDTA_esperado = a*a*CD
print("\nCovarianza de la matriz afin esperada:")
print(CDTA_esperado)

Matriz transformada afin:
[[55 25]
 [95 75]
 [65 15]]

Media de la matriz base:
[6.66666667 3.33333333]

Media de la matriz afin:
[71.66666667 38.33333333]

Covarianza de la matriz base:
[[ 4.33333333  6.16666667]
 [ 6.16666667 10.33333333]]

Covarianza de la matriz afin:
[[ 433.33333333  616.66666667]
 [ 616.66666667 1033.33333333]]

Media de la matriz afin esperada:
[71.66666667 38.33333333]

Covarianza de la matriz afin esperada:
[[ 433.33333333  616.66666667]
 [ 616.66666667 1033.33333333]]
