# Exercise 1.2

## A

In [13]:
import numpy as np

In [14]:
D = np.array([[5, 2], [9, 7], [6, 1]])
print("\nMatriz base:")
print(D)
DT = D*2
print("\nMatriz base transformada:")
print(DT)

CD = np.cov(D, rowvar=False, bias=True)
print("\nCovarianza de la matriz base:")
print(CD)
CDT = np.cov(DT, rowvar=False, bias=True)
print("\nCovarianza de la matriz base transformada:")
print(CDT)

#Se pone rowvar (Variable de fila) en falso, ya que nuestras variables estan representadas por columnas, no por filas


Matriz base:
[[5 2]
 [9 7]
 [6 1]]

Matriz base transformada:
[[10  4]
 [18 14]
 [12  2]]

Covarianza de la matriz base:
[[2.88888889 4.11111111]
 [4.11111111 6.88888889]]

Covarianza de la matriz base transformada:
[[11.55555556 16.44444444]
 [16.44444444 27.55555556]]


Tenemos la matriz D, la base de nuestro ejercicio y tenemos la transformación DT, multiplicando cada dato de la matriz por 2, para luego calcular las covarianzas de ambas matrices mostrando que la transformacion de los datos puede cambiar el resultado de la covarianza

## B

In [15]:
a = 10
b = 5

DTA = a * D + b
print("Matriz transformada afin:")
print(DTA)

mu = np.mean(D, axis=0)
print("\nMedia de la matriz base:")
print(mu)

mut = np.mean(DTA, axis=0)
print("\nMedia de la matriz afin:")
print(mut)
#Se pone axis = 0 para que calule la media de cada columna

print("\nCovarianza de la matriz base:")
print(CD)

CDTA = np.cov(DTA, rowvar=False, bias=True)
print("\nCovarianza de la matriz afin:")
print(CDTA)

mut_esperado = a * mu + b
print("\nMedia de la matriz afin esperada:")
print(mut_esperado)

CDTA_esperado = a*a*CD
print("\nCovarianza de la matriz afin esperada:")
print(CDTA_esperado)

Matriz transformada afin:
[[55 25]
 [95 75]
 [65 15]]

Media de la matriz base:
[6.66666667 3.33333333]

Media de la matriz afin:
[71.66666667 38.33333333]

Covarianza de la matriz base:
[[2.88888889 4.11111111]
 [4.11111111 6.88888889]]

Covarianza de la matriz afin:
[[288.88888889 411.11111111]
 [411.11111111 688.88888889]]

Media de la matriz afin esperada:
[71.66666667 38.33333333]

Covarianza de la matriz afin esperada:
[[288.88888889 411.11111111]
 [411.11111111 688.88888889]]


Para una transformación afin que es $$f_j(x) = ax + b$$ para el calculo de la media y covarianza de la matriz transformada seria:

Media:
$$μ_{j}t = 1/n\sum_{i=1}^nf_j(D_{i,j})=1/n\sum_{i=1}^aμ_j+b=aμ_j+b$$

Covarianza:
$$σ_{ij}t = 1/n\sum_{k=1}^n(f_i(D_{k,i}) - μ_{j}t)(f_j(D_{k,j})-μ_{j}t)$$
$$=1/n\sum_{k=1}^na_ia_j(σ_{ij})$$
$$=a_ia_jσ_{ij}$$

Donde $μ_{j}t$ es la media de la matriz transformada, $μ_j$ la media de la matriz base, $σ_{ij}t$ es la covarianza de la matriz transformada y $σ_{ij}$ la covarianza de la matriz base

Para este punto tenemos la matriz DTA, que es la matriz D tranformada afin, que esta transformación consiste en una transformación lineal seguida de una traslación, donde se calcula la media y la covarianza de la matriz transformada con funciones de Numpy, para luego por medio de las ecuaciones presentadas μj=ajμj+b y σij=aiajσij, estas para la matriz tranformada, mostrar que los resultados de las funciones dan igual al de las ecuaciones

## C

In [16]:
CRD = np.corrcoef(D, rowvar=False)
print("\nCorrelación matriz base:")
print(CRD)

CRDTA = np.corrcoef(DTA, rowvar=False)
print("\nCorrelación matriz afin:")
print(CRDTA)


Correlación matriz base:
[[1.         0.92155064]
 [0.92155064 1.        ]]

Correlación matriz afin:
[[1.         0.92155064]
 [0.92155064 1.        ]]


Esta propiedad nos da a entender que sin importar las transformaciones la correlación va a ser la misma