# Exercise 1.2

## A

In [10]:
import numpy as np

In [14]:
D = np.array([[5, 2], [9, 7], [6, 1]])
print("\nMatriz base:")
print(D)
DT = D*2
print("\nMatriz base transformada:")
print(DT)

CD = np.cov(D, rowvar=False)
print("\nCovarianza de la matriz base:")
print(CD)
CDT = np.cov(DT, rowvar=False)
print("\nCovarianza de la matriz base transformada:")
print(CDT)

#Se pone rowvar (Variable de fila) en falso, ya que nuestras variables estan representadas por columnas, no por filas


Matriz base:
[[5 2]
 [9 7]
 [6 1]]

Matriz base transformada:
[[10  4]
 [18 14]
 [12  2]]

Covarianza de la matriz base:
[[ 4.33333333  6.16666667]
 [ 6.16666667 10.33333333]]

Covarianza de la matriz base transformada:
[[17.33333333 24.66666667]
 [24.66666667 41.33333333]]


Tenemos la matriz D, la base de nuestro ejercicio y tenemos la transformación DT, multiplicando cada dato de la matriz por 2, para luego calcular las covarianzas de ambas matrices mostrando que la transformacion de los datos puede cambiar el resultado de la covarianza

## B

In [12]:
a = 10
b = 5

DTA = a * D + b
print("Matriz transformada afin:")
print(DTA)

mu = np.mean(D, axis=0)
print("\nMedia de la matriz base:")
print(mu)

mut = np.mean(DTA, axis=0)
print("\nMedia de la matriz afin:")
print(mut)
#Se pone axis = 0 para que calule la media de cada columna

print("\nCovarianza de la matriz base:")
print(CD)

CDTA = np.cov(DTA, rowvar=False)
print("\nCovarianza de la matriz afin:")
print(CDTA)

mut_esperado = a * mu + b
print("\nMedia de la matriz afin esperada:")
print(mut_esperado)

CDTA_esperado = a*a*CD
print("\nCovarianza de la matriz afin esperada:")
print(CDTA_esperado)

Matriz transformada afin:
[[55 25]
 [95 75]
 [65 15]]

Media de la matriz base:
[6.66666667 3.33333333]

Media de la matriz afin:
[71.66666667 38.33333333]

Covarianza de la matriz base:
[[ 4.33333333  6.16666667]
 [ 6.16666667 10.33333333]]

Covarianza de la matriz afin:
[[ 433.33333333  616.66666667]
 [ 616.66666667 1033.33333333]]

Media de la matriz afin esperada:
[71.66666667 38.33333333]

Covarianza de la matriz afin esperada:
[[ 433.33333333  616.66666667]
 [ 616.66666667 1033.33333333]]


Para este punto tenemos la matriz DTA, que es la matriz D tranformada afin, que esta transformación consiste en una transformación lineal seguida de una traslación, donde se calcula la media y la covarianza de la matriz transformada con funciones de Numpy, para luego por medio de las ecuaciones presentadas μj=ajμj+b y σij=aiajσij, estas para la matriz tranformada, mostrar que los resultados de las funciones dan igual al de las ecuaciones

## C

In [13]:
CRD = np.corrcoef(D, rowvar=False)
print("\nCorrelación matriz base:")
print(CRD)

CRDTA = np.corrcoef(DTA, rowvar=False)
print("\nCorrelación matriz afin:")
print(CRDTA)


Correlación matriz base:
[[1.         0.92155064]
 [0.92155064 1.        ]]

Correlación matriz afin:
[[1.         0.92155064]
 [0.92155064 1.        ]]


Esta propiedad nos da a entender que sin importar las transformaciones la correlación va a ser la misma